# test_env.py
from config.settings import (
    TINKOFF_API_TOKEN,
    TINKOFF_ACCOUNT_ID,
    TINKOFF_SANDBOX,
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID,
)

print("TINKOFF_API_TOKEN:", TINKOFF_API_TOKEN)
print("TINKOFF_ACCOUNT_ID:", TINKOFF_ACCOUNT_ID)
print("TINKOFF_SANDBOX:", TINKOFF_SANDBOX)
print("TELEGRAM_BOT_TOKEN:", TELEGRAM_BOT_TOKEN)
print("TELEGRAM_CHAT_ID:", TELEGRAM_CHAT_ID)